#!/usr/bin/env python3
"""Curate a vetted batch of well-known scholarships into the review queue.

Same honest pattern as the original Nevada seeds: real programs + their OFFICIAL source URLs,
conservative data (amounts/deadlines left null rather than guessed), every record `needs-review`
so a human verifies the specifics against the source before it goes live. This is deliberate
curation, not a flaky crawl — reliable volume that a person then approves.

Each entry's info_url is fetched first; dead links are skipped so we never queue a broken record.

    api/venv/bin/python tools/seed_curated.py [--dry-run]
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import discover as d  # reuse fetch + schema validator + slug  # noqa: E402

TODAY = date.today().isoformat()

# (name, sponsor, sponsor_type, type, basis, [levels], info_url, [eligibility notes])
CURATED = [
    ("The Gates Scholarship", "The Gates Scholarship", "foundation", "scholarship", "need",
     ["high-school-senior"], "https://www.thegatesscholarship.org/scholarship",
     ["Pell-eligible high school seniors from minority backgrounds", "Last-dollar; full cost of attendance"]),
    ("QuestBridge National College Match", "QuestBridge", "foundation", "scholarship", "need",
     ["high-school-senior"], "https://www.questbridge.org/high-school-students/national-college-match",
     ["High-achieving high school seniors from low-income households", "Full four-year scholarships to partner colleges"]),
    ("Coca-Cola Scholars Program", "Coca-Cola Scholars Foundation", "foundation", "scholarship", "merit",
     ["high-school-senior"], "https://www.coca-colascholarsfoundation.org/programs/coca-cola-scholars-program/",
     ["Achievement-based award for graduating high school seniors"]),
    ("Hispanic Scholarship Fund", "Hispanic Scholarship Fund", "foundation", "scholarship", "merit-need",
     ["high-school-senior", "undergraduate", "graduate"], "https://www.hsf.net/scholarship",
     ["Students of Hispanic heritage", "Minimum GPA and FAFSA/Dream Act application required (verify)"]),
    ("Jack Kent Cooke Foundation College Scholarship", "Jack Kent Cooke Foundation", "foundation", "scholarship", "merit-need",
     ["high-school-senior"], "https://www.jkcf.org/our-scholarships/college-scholarship-program/",
     ["High-achieving high school seniors with financial need"]),
    ("Dell Scholars Program", "Michael & Susan Dell Foundation", "foundation", "scholarship", "need",
     ["high-school-senior"], "https://www.dellscholars.org/scholarship/",
     ["Students in approved college-readiness programs; grit-focused", "Verify program participation requirement"]),
    ("Horatio Alger National Scholarship", "Horatio Alger Association", "foundation", "scholarship", "need",
     ["high-school-senior"], "https://scholars.horatioalger.org/",
     ["Students who have faced and overcome adversity, with financial need"]),
    ("Ron Brown Scholar Program", "Ron Brown Scholar Fund", "foundation", "scholarship", "identity",
     ["high-school-senior"], "https://www.ronbrown.org/",
     ["Black/African American high school seniors"]),
    ("Jackie Robinson Foundation Scholarship", "Jackie Robinson Foundation", "foundation", "scholarship", "identity",
     ["high-school-senior"], "https://www.jackierobinson.org/apply/",
     ["Minority high school seniors with financial need and leadership"]),
    ("Elks National Foundation Most Valuable Student", "Elks National Foundation", "civic", "scholarship", "merit-need",
     ["high-school-senior"], "https://www.elks.org/scholars/scholarships/mvs.cfm",
     ["U.S. high school seniors; leadership + financial need"]),
    ("Coolidge Scholarship", "Calvin Coolidge Presidential Foundation", "foundation", "scholarship", "merit",
     ["high-school-senior"], "https://www.coolidgescholars.org/",
     ["Full-ride merit scholarship; apply as a high school junior (verify timing)"]),
    ("Davidson Fellows Scholarship", "Davidson Institute", "foundation", "scholarship", "merit",
     ["high-school", "undergraduate"], "https://www.davidsongifted.org/gifted-programs/fellows-scholarship/",
     ["Students 18 or younger with a significant project in STEM, literature, music, or philosophy"]),
    ("GE-Reagan Foundation Scholarship", "Ronald Reagan Presidential Foundation", "foundation", "scholarship", "merit",
     ["high-school-senior"], "https://www.reaganfoundation.org/education/scholarship-programs/ge-reagan-foundation-scholarship-program/",
     ["Leadership, drive, integrity, citizenship; financial need considered"]),
    ("National Merit Scholarship Program", "National Merit Scholarship Corporation", "foundation", "scholarship", "merit",
     ["high-school-senior"], "https://www.nationalmerit.org/",
     ["Qualify via the PSAT/NMSQT in the junior year"]),

    # --- batch 2 (2026-05-27): wider "feelers" — identity · field · trades · military · DACA · NV-local · STEM.
    # All URLs verified live; specifics left null for human review against the source.
    ("Burger King Scholars (BK McLamore Foundation)", "Burger King Foundation", "foundation", "scholarship", "merit-need",
     ["high-school-senior"], "https://www.burgerkingscholars.com/",
     ["Graduating high school seniors (US/Canada/Puerto Rico)", "GPA + financial need + work/community involvement"]),
    ("Amazon Future Engineer Scholarship", "Amazon", "employer", "scholarship", "need",
     ["high-school-senior"], "https://www.amazonfutureengineer.com/scholarships",
     ["Students pursuing computer science from underserved/underrepresented backgrounds", "Includes a paid internship"]),
    ("UNCF General Scholarship", "United Negro College Fund", "foundation", "scholarship", "identity",
     ["high-school-senior", "undergraduate"], "https://uncf.org/scholarships",
     ["Primarily African American students with financial need", "One application matches to many UNCF programs"]),
    ("APIA Scholars Scholarship", "Asian & Pacific Islander American Scholarship Fund", "foundation", "scholarship", "identity",
     ["high-school-senior", "undergraduate"], "https://apiascholars.org/scholarship/",
     ["Students of Asian and/or Pacific Islander heritage", "Financial need; first-gen prioritized"]),
    ("American Indian College Fund Scholarships", "American Indian College Fund", "foundation", "scholarship", "identity",
     ["undergraduate", "graduate"], "https://collegefund.org/students/scholarships/",
     ["Native American and Alaska Native students at accredited institutions / tribal colleges"]),
    ("AAUW Fellowships & Grants", "American Association of University Women", "foundation", "fellowship", "merit-need",
     ["graduate"], "https://www.aauw.org/resources/programs/fellowships-grants/",
     ["Women pursuing graduate or postgraduate study", "Several distinct fellowship tracks"]),
    ("Barry Goldwater Scholarship", "Barry Goldwater Scholarship Foundation", "federal", "scholarship", "merit",
     ["undergraduate"], "https://goldwaterscholarship.gov/",
     ["Sophomores/juniors pursuing research careers in STEM", "Nominated by their institution"]),
    ("mikeroweWORKS Work Ethic Scholarship", "mikeroweWORKS Foundation", "foundation", "scholarship", "other",
     ["vocational"], "https://www.mikeroweworks.org/scholarship/",
     ["Students pursuing skilled trades / technical training", "Work-ethic essay + S.W.E.A.T. pledge"]),
    ("Tillman Scholars", "Pat Tillman Foundation", "foundation", "scholarship", "service",
     ["undergraduate", "graduate"], "https://pattillmanfoundation.org/",
     ["Active-duty service members, veterans, and military spouses", "Leadership and service focus"]),
    ("Scholarships for Military Children", "Fisher House Foundation", "foundation", "scholarship", "other",
     ["high-school-senior", "undergraduate"], "https://militaryscholar.org/",
     ["Children of active-duty, retired, or eligible military families"]),
    ("TheDream.US National Scholarship", "TheDream.US", "foundation", "scholarship", "need",
     ["high-school-senior", "community-college"], "https://www.thedream.us/scholarships/",
     ["Undocumented students with DACA or TPS (or eligible)", "Attend a partner college"]),
    ("Golden Door Scholars", "Golden Door Scholars", "foundation", "scholarship", "need",
     ["high-school-senior"], "https://www.goldendoorscholars.org/",
     ["High-performing students facing barriers, including DACA/undocumented", "Partner-college network"]),
    ("Generation Google Scholarship", "Google", "employer", "scholarship", "identity",
     ["undergraduate", "graduate"], "https://buildyourfuture.withgoogle.com/scholarships",
     ["Computer science students from historically underrepresented groups", "Leadership + academic achievement"]),
    ("Taco Bell Live Más Scholarship", "Taco Bell Foundation", "foundation", "scholarship", "other",
     ["high-school-senior", "undergraduate"], "https://www.tacobellfoundation.org/live-mas-scholarship/",
     ["Passion-driven video application (not GPA/test based)", "Ages 16-26"]),
    ("Equitable Excellence Scholarship", "Equitable Foundation", "foundation", "scholarship", "merit",
     ["high-school-senior"], "https://equitable.com/foundation/equitable-excellence-scholarship",
     ["High school seniors who show drive and contribution to community"]),
    ("Point Foundation Flagship Scholarship", "Point Foundation", "foundation", "scholarship", "identity",
     ["undergraduate", "graduate"], "https://pointfoundation.org/",
     ["LGBTQ students with leadership and financial need"]),
    ("NSNA Foundation Nursing Scholarships", "National Student Nurses' Association Foundation", "foundation", "scholarship", "field",
     ["undergraduate"], "https://www.nsna.org/",
     ["Enrolled nursing students", "Academic achievement + financial need"]),
    # NOTE: NV-specific scholarships (Nevada Women's Fund, Public Education Foundation, UNLV) live
    # directly in data/NV/ as NV-scoped records — this seeder is national-only (build() forces US).

    # --- batch 3 (2026-05-27): STEM societies · public service · fields/trades · more identity ---
    ("Stamps Scholars", "Stamps Family Charitable Foundation", "foundation", "scholarship", "merit",
     ["high-school-senior"], "https://stampsscholars.org/",
     ["Full-cost merit award at partner universities", "Leadership and impact focus"]),
    ("Hagan Scholarship", "Hagan Scholarship Foundation", "foundation", "scholarship", "need",
     ["high-school-senior"], "https://haganscholarship.org/",
     ["Rural / small-town public high school seniors with financial need", "Verify eligible-county list"]),
    ("NSBE Scholarships", "National Society of Black Engineers", "foundation", "scholarship", "identity",
     ["undergraduate", "graduate"], "https://www.nsbe.org/scholarships",
     ["NSBE members pursuing engineering and technical degrees"]),
    ("Regeneron Science Talent Search", "Society for Science", "foundation", "prize", "merit",
     ["high-school-senior"], "https://www.societyforscience.org/regeneron-sts/",
     ["Original STEM research competition for high school seniors"]),
    ("Discover Student Loans Scholarship", "Discover", "employer", "scholarship", "other",
     ["high-school-senior", "undergraduate"], "https://www.discover.com/student-loans/scholarships/",
     ["Recurring award with a quick entry; verify current terms"]),
    ("Scholarship America Dream Award", "Scholarship America", "foundation", "scholarship", "need",
     ["undergraduate"], "https://scholarshipamerica.org/students/browse-scholarships/",
     ["Renewable, need-based award for students past their first year"]),
    ("Gen and Kelly Tanabe Scholarship", "Gen and Kelly Tanabe", "private", "scholarship", "merit",
     ["high-school", "undergraduate", "graduate"], "https://www.genkellyscholarship.com/",
     ["Open to a wide range of students; short essay"]),
    ("Courage to Grow Scholarship", "Courage to Grow", "private", "scholarship", "other",
     ["high-school-senior", "undergraduate"], "https://couragetogrowscholarship.com/",
     ["Recurring award; short essay, low barrier to entry"]),
    ("DoSomething.org Scholarships", "DoSomething.org", "foundation", "scholarship", "service",
     ["high-school", "undergraduate"], "https://www.dosomething.org/us/about/easy-scholarships",
     ["Earned by joining volunteer / social-action campaigns; no GPA or essay"]),
    ("AICPA Legacy Scholarships", "AICPA Foundation", "foundation", "scholarship", "field",
     ["undergraduate", "graduate"], "https://www.aicpa-cima.com/membership/landing/scholarships-and-awards",
     ["Accounting students; may require student-affiliate membership"]),
    ("Davis-Putter Scholarship Fund", "Davis-Putter Scholarship Fund", "foundation", "scholarship", "need",
     ["undergraduate", "graduate"], "https://www.davisputter.org/",
     ["Students active in movements for social and economic justice, with financial need"]),
    ("American Welding Society Scholarships", "American Welding Society Foundation", "foundation", "scholarship", "field",
     ["vocational", "undergraduate"], "https://www.aws.org/foundation/page/scholarships",
     ["Students pursuing welding and welding-engineering education"]),
    ("National FFA Scholarships", "National FFA Organization", "foundation", "scholarship", "field",
     ["high-school-senior", "undergraduate"], "https://www.ffa.org/participate/grants-and-scholarships/",
     ["FFA members; agriculture and many other fields", "One application for many awards"]),
    ("Actuarial Foundation Scholarships", "The Actuarial Foundation", "foundation", "scholarship", "field",
     ["undergraduate"], "https://www.actuarialfoundation.org/scholarships/",
     ["Students pursuing actuarial science / mathematics"]),
    ("NACME Scholarships", "National Action Council for Minorities in Engineering", "foundation", "scholarship", "identity",
     ["undergraduate"], "https://www.nacme.org/scholarships",
     ["Underrepresented-minority students in engineering at NACME partner schools"]),
    ("Truman Scholarship", "Harry S. Truman Scholarship Foundation", "federal", "scholarship", "service",
     ["undergraduate"], "https://www.truman.gov/",
     ["College juniors committed to public-service careers", "Nominated by their institution"]),
    ("Udall Undergraduate Scholarship", "Udall Foundation", "federal", "scholarship", "field",
     ["undergraduate"], "https://www.udall.gov/",
     ["Students in environment fields, or Native American students in tribal health/policy"]),
    ("Hispanic Heritage Youth Awards", "Hispanic Heritage Foundation", "foundation", "scholarship", "identity",
     ["high-school-senior"], "https://hispanicheritage.org/programs/leadership/youth-awards/",
     ["Latino high school seniors; regional and category awards"]),
    ("ASME Scholarships", "American Society of Mechanical Engineers", "foundation", "scholarship", "field",
     ["undergraduate", "graduate"], "https://www.asme.org/asme-programs/students-and-faculty/scholarships",
     ["ASME student members in mechanical engineering"]),
    ("AISES Scholarships", "American Indian Science and Engineering Society", "foundation", "scholarship", "identity",
     ["undergraduate", "graduate"], "https://aises.org/students/scholarships/",
     ["Native American / Indigenous students in STEM"]),

    # ---- 2026-06-16 batch: identity / diversity / disability ----
    ("Thurgood Marshall College Fund Scholarships", "Thurgood Marshall College Fund", "foundation", "scholarship", "merit-need",
     ["undergraduate", "graduate"], "https://tmcf.org/scholarships/open-scholarships/",
     ["For students at TMCF member HBCUs/PBIs and other eligible accredited schools", "One general application auto-matches to open scholarships"]),
    ("100 Black Men of America National Scholarship", "100 Black Men of America, Inc.", "civic", "scholarship", "merit-need",
     ["high-school-senior", "undergraduate"], "https://100blackmen.org/four-for-the-future/education/national-scholarship-program/",
     ["Graduating seniors or full-time undergrads, 2.5+ GPA, U.S. citizen/PR", "Financial need + community service; awards paid to the institution"]),
    ("ScholarSHPE Scholarship Program", "Society of Hispanic Professional Engineers", "civic", "scholarship", "field",
     ["high-school-senior", "undergraduate", "graduate", "vocational"], "https://shpe.org/engage/programs/scholarshpe/",
     ["Active SHPE member pursuing a STEM degree, 2.5+ GPA", "One ScholarSHPE Common Application matches multiple awards"]),
    ("LULAC National Scholarship Fund", "LULAC National Educational Service Centers", "civic", "scholarship", "identity",
     ["undergraduate", "community-college", "graduate", "vocational"], "https://www.lnesc.org/scholarships/lulac/",
     ["U.S. citizen, permanent resident, or DACA recipient enrolled full-time", "Requires a participating LULAC Council in your area"]),
    ("MALDEF Law School Scholarship Program", "Mexican American Legal Defense and Educational Fund", "civic", "scholarship", "identity",
     ["graduate"], "https://www.maldef.org/resources/leadership-programs/law-school-scholarship-program/",
     ["Open to any student enrolled at an accredited U.S. law school", "Selected on commitment to advancing Latino civil rights"]),
    ("Cobell Scholarship", "Indigenous Education, Inc.", "foundation", "scholarship", "identity",
     ["undergraduate", "community-college", "graduate", "vocational"], "https://cobellscholar.org/our-scholarships/",
     ["Enrolled member of a U.S. federally recognized tribe or Alaska Native Corporation", "Undergraduate, graduate, vocational/trade, and summer tracks"]),
    ("IHS Scholarship Program", "Indian Health Service", "federal", "scholarship", "field",
     ["undergraduate", "graduate"], "https://www.ihs.gov/scholarship/scholarships/",
     ["Member (or descendant, some tracks) of a federally recognized tribe/Alaska Native village", "Health-profession programs; Health Professions track carries an IHS service commitment"]),
    ("JACL National Scholarship Program", "Japanese American Citizens League", "civic", "scholarship", "identity",
     ["high-school-senior", "undergraduate", "graduate"], "https://jacl.org/scholarships",
     ["Must be an active National JACL member", "Freshman, undergraduate, graduate, law, and creative/performing arts tracks"]),
    ("Korean American Scholarship Foundation Scholarship", "Korean American Scholarship Foundation", "foundation", "scholarship", "identity",
     ["high-school", "undergraduate", "graduate"], "https://www.kasf.org/scholarships/",
     ["Students of Korean heritage enrolled full-time in the U.S., 3.0+ GPA", "Apply via the regional chapter covering your school"]),
    ("P.E.O. STAR Scholarship", "P.E.O. International", "civic", "scholarship", "merit",
     ["high-school-senior"], "https://www.peointernational.org/educational-support/star-scholarship/",
     ["Women in their final year of high school with strong leadership and academics", "Plan to attend an accredited U.S./Canada institution; chapter-recommended"]),
    ("Jeannette Rankin National Scholar Grant", "Jeannette Rankin Foundation", "foundation", "grant", "need",
     ["undergraduate", "community-college", "vocational"], "https://rankinfoundation.org/national-scholar-grant/",
     ["Women and nonbinary students age 35 or older with financial need", "First associate's/bachelor's or technical-vocational training; renewable"]),
    ("LEAGUE Foundation Scholarship", "LEAGUE Foundation", "foundation", "scholarship", "identity",
     ["high-school-senior"], "https://www.leaguefoundation.org/",
     ["Graduating U.S. senior who self-identifies as LGBTQ+ or a supporter", "U.S. citizen/legal resident, 3.0+ GPA, accepted to an accredited U.S. college"]),
    ("Out to Innovate Scholarship", "Out to Innovate (NOGLSTP)", "foundation", "scholarship", "identity",
     ["undergraduate"], "https://www.outtoinnovate.org/scholarships",
     ["LGBTQ+ undergraduate in a STEM or STEM-teaching major", "Completed 2+ years of post-high-school education, 2.75+ GPA"]),
    ("Anne Ford Scholarship", "National Center for Learning Disabilities", "foundation", "scholarship", "identity",
     ["high-school-senior", "undergraduate"], "https://ncld.org/scholarships-awards/anne-ford-scholarship/",
     ["Graduating senior enrolling full-time in a 4-year bachelor's program", "Documented learning disability (ADHD + LD encouraged)"]),
    ("Allegra Ford Thomas Scholarship", "National Center for Learning Disabilities", "foundation", "scholarship", "identity",
     ["high-school-senior", "community-college", "vocational"], "https://ncld.org/scholarships-awards/allegra-ford-thomas-scholarship/",
     ["Graduating senior entering a 2-year community college, vocational, or technical program", "Documented learning disability"]),
    ("ACB Scholarship Program", "American Council of the Blind", "civic", "scholarship", "identity",
     ["high-school-senior", "undergraduate", "graduate", "vocational"], "https://www.acb.org/scholarships",
     ["Legally blind students at a U.S. post-secondary institution", "Most awards require a 3.0+ GPA"]),
    ("Paul & Daisy Soros Fellowships for New Americans", "Paul & Daisy Soros Fellowships for New Americans", "foundation", "fellowship", "identity",
     ["graduate"], "https://pdsoros.org/",
     ["Immigrant or child of two immigrant parents (a 'New American'), age 30 or younger", "Enrolling full-time in a U.S. graduate/professional degree program"]),
    ("Patsy Takemoto Mink Education Support Award", "Patsy Takemoto Mink Education Foundation", "foundation", "scholarship", "need",
     ["undergraduate", "graduate", "community-college", "vocational"], "https://www.patsyminkfoundation.org/education-support-application",
     ["Low-income mothers (women age 17+) with minor children", "Enrolled in an accredited U.S. postsecondary program"]),
    ("MPOWER Global Citizen Scholarship", "MPOWER Financing", "private", "scholarship", "identity",
     ["undergraduate", "graduate"], "https://www.mpowerfinancing.com/scholarships/global-citizen",
     ["International students, DACA recipients, or U.S./Canadian permanent residents (citizens ineligible)", "Enrolled in/accepted to a full-time degree at an MPOWER-supported U.S./Canada school"]),

    # ---- 2026-06-16 batch: STEM / field / professional ----
    ("ACS Catalyst Scholarship", "American Chemical Society", "foundation", "scholarship", "field",
     ["high-school-senior", "undergraduate"], "https://www.acs.org/funding/scholarships-fellowships/catalyst-scholarship.html",
     ["Chemistry / chemical-sciences majors", "U.S. citizen/PR, 3.0+ GPA, demonstrated financial need; renewable"]),
    ("SAE Engineering Scholarships", "SAE International", "foundation", "scholarship", "field",
     ["high-school-senior", "undergraduate", "graduate"], "https://www.sae.org/participate/scholarships",
     ["Students pursuing engineering/STEM (mobility, automotive, aerospace, commercial-vehicle)", "One application matches to multiple named scholarships"]),
    ("AIAA Foundation Undergraduate Scholarships", "American Institute of Aeronautics and Astronautics", "foundation", "scholarship", "field",
     ["undergraduate", "graduate"], "https://aiaa.org/get-involved/university-students/undergraduate-scholarships-graduate-awards/",
     ["AIAA student members in aerospace-related science/engineering", "One application window mid-Oct through end of Jan"]),
    ("IEEE PES Scholarship Plus Initiative", "IEEE Power & Energy Society", "foundation", "scholarship", "field",
     ["undergraduate"], "https://www.ee-scholarship.org/",
     ["Electrical engineering undergrads (3.0+ GPA, ABET program) committed to power & energy", "U.S./Puerto Rico/Canada"]),
    ("SME Education Foundation Scholarships", "SME Education Foundation", "foundation", "scholarship", "field",
     ["high-school-senior", "community-college", "undergraduate"], "https://scholarships.smeef.org/",
     ["Manufacturing / engineering-technology fields (CNC, robotics, mechatronics, automation)", "60+ named awards via one application"]),
    ("TYLENOL Future Care Scholarship", "Kenvue (TYLENOL)", "employer", "scholarship", "field",
     ["undergraduate", "graduate"], "https://www.tylenol.com/tylenol-future-care-scholarship",
     ["Medicine, nursing, pharmacy, or other patient-care healthcare majors with 1+ year remaining", "U.S./PR/DC residents"]),
    ("NSA Scholarship Foundation Scholarship", "National Society of Accountants Scholarship Foundation", "foundation", "scholarship", "field",
     ["undergraduate", "graduate"], "https://nsacct.org/nsaf-scholarships/",
     ["Declared accounting majors at accredited U.S. schools, 3.0+ GPA", "U.S./Canadian citizens"]),
    ("AOPA Flight Training Scholarships", "AOPA Foundation", "foundation", "scholarship", "field",
     ["high-school", "undergraduate", "vocational"], "https://www.aopa.org/training-and-safety/learn-to-fly/aviation-scholarships",
     ["AOPA members pursuing a pilot certificate or advanced rating", "High schoolers 16-18, teachers, and adults eligible"]),
    ("National Press Club Scholarships", "National Press Club Journalism Institute", "civic", "scholarship", "field",
     ["high-school", "undergraduate", "graduate"], "https://www.press.org/students",
     ["Students pursuing journalism (sports writing, broadcast, diversity in journalism)", "Several awards, some renewable"]),
    ("Palantir Women in Technology Scholarship", "Palantir Technologies", "employer", "scholarship", "field",
     ["undergraduate"], "https://www.palantir.com/careers/students/scholarship/wit-north-america/",
     ["Undergraduate women majoring in computer science, software engineering, or a related technical field", "Open to students at U.S./Canada/Mexico institutions"]),
    ("National Garden Clubs Scholarships", "National Garden Clubs, Inc.", "foundation", "scholarship", "field",
     ["undergraduate", "graduate"], "https://gardenclub.org/college-scholarships",
     ["Horticulture, environment, conservation, botany, forestry, plant/wildlife science, landscape design majors", "U.S. citizen/PR, 3.25+ GPA, sophomore year and up"]),
    ("DoD SMART Scholarship-for-Service", "U.S. Department of Defense", "federal", "scholarship", "field",
     ["high-school-senior", "undergraduate", "graduate"], "https://www.smartscholarship.org/smart",
     ["STEM majors who accept post-graduation DoD civilian employment", "Full tuition, annual stipend, health insurance, and a guaranteed job; U.S. citizens"]),

    # ---- 2026-06-16 batch: trades / vocational / corporate / general ----
    ("Imagine America High School Scholarship", "Imagine America Foundation", "foundation", "scholarship", "need",
     ["high-school-senior", "vocational"], "https://imagine-america.org/scholarships/high-school-scholarships",
     ["Graduating seniors enrolling at a participating career/trade college", "Each high school may nominate up to five seniors"]),
    ("TechForce Foundation Scholarships", "TechForce Foundation", "foundation", "scholarship", "merit-need",
     ["vocational", "community-college", "undergraduate"], "https://techforce.org/scholarships/",
     ["Students in accredited vehicle/technician programs (auto, diesel, aviation, marine, welding, HVAC)", "One general application; FAFSA/financial hardship required"]),
    ("SkillsUSA Scholarships and Grants", "SkillsUSA", "civic", "scholarship", "field",
     ["high-school", "vocational", "community-college"], "https://www.skillsusa.org/recognition/scholarships-and-grants/",
     ["Active SkillsUSA members in career & technical education", "Multiple national awards (NTHS/SkillsUSA, Marsha Daves, NAPA)"]),
    ("National Technical Honor Society Scholarship", "National Technical Honor Society", "civic", "scholarship", "merit",
     ["high-school-senior", "vocational", "community-college", "undergraduate"], "https://nths.org/",
     ["Active NTHS members in good standing (CTE students)", "Apply via the NTHS member portal"]),
    ("SKILLED Nation Scholarship", "SKILLED Nation", "foundation", "scholarship", "field",
     ["high-school-senior", "vocational", "community-college"], "https://skilled-nation.org/apply/skilled-scholarships",
     ["Students pursuing skilled-trade training (construction, healthcare, manufacturing, energy, transportation, tech)", "One universal application matches multiple awards (formerly SkillPointe)"]),
    ("Bridging the Dream Scholarship for High School Seniors", "The Sallie Mae Fund", "employer", "scholarship", "merit-need",
     ["high-school-senior"], "https://www.salliemae.com/about/scholarship-opportunities/bridging-the-dream-scholarship-for-high-school-seniors/",
     ["Pell-eligible seniors heading to a 2-/4-year college or technical program", "Minimum 2.75 GPA"]),
    ("Chick-fil-A Remarkable Futures Scholarship", "Chick-fil-A, Inc.", "employer", "scholarship", "merit",
     ["high-school-senior", "undergraduate", "graduate"], "https://www.chick-fil-a.com/remarkable-futures-scholarships",
     ["Open to employed Chick-fil-A restaurant Team Members", "Tiers of $1,000, $2,500, and $25,000"]),
    ("Dr Pepper Tuition Giveaway", "Dr Pepper (Keurig Dr Pepper)", "employer", "scholarship", "merit",
     ["undergraduate", "community-college"], "https://www.drpeppertuition.com/",
     ["U.S. students ages 18-24; no minimum GPA or major", "Video contest; large per-winner awards"]),
    ("Cameron Impact Scholarship", "Bryan Cameron Education Foundation", "foundation", "scholarship", "merit",
     ["high-school-senior"], "https://www.bryancameroneducationfoundation.org/scholarship",
     ["Full-tuition merit award for ~15 seniors; 3.7+ unweighted GPA, U.S. citizen", "Closes at the earlier of the deadline or 3,000 applications"]),
    ("BigFuture Scholarships", "College Board", "foundation", "scholarship", "other",
     ["high-school"], "https://bigfuture.collegeboard.org/pay-for-college/bigfuture-scholarships",
     ["No essay, GPA, or test-score requirement; earn entries by completing college-planning steps", "Monthly drawings open to U.S./territory students"]),
    ("McDonald's HACER National Scholarship", "McDonald's", "employer", "scholarship", "identity",
     ["high-school-senior"], "https://www.mcdonalds.com/us/en-us/community/hacer.html",
     ["U.S. seniors with at least one parent of Hispanic/Latino heritage", "~$1M awarded annually nationwide"]),
    ("Obama-Chesky Voyager Scholarship for Public Service", "The Obama Foundation", "foundation", "scholarship", "merit-need",
     ["undergraduate"], "https://www.obama.org/programs/voyager-scholarship/",
     ["Students entering junior year at a 4-year U.S. college pursuing public service; financial need required", "U.S. citizen/PR/DACA; includes a funded 'Summer Voyage'"]),

    # ---- 2026-06-16 batch: service / military / civic / arts / competitions ----
    ("Folds of Honor Higher Education Scholarship", "Folds of Honor Foundation", "foundation", "scholarship", "service",
     ["undergraduate", "graduate", "vocational"], "https://foldsofhonor.org/scholarships/military-scholarships/",
     ["Children and spouses of fallen or disabled U.S. service members and first responders", "Application window Feb 1 - Mar 31"]),
    ("AMVETS National Scholarship", "AMVETS (American Veterans)", "civic", "scholarship", "service",
     ["undergraduate"], "https://amvets.org/scholarships/",
     ["Veterans, active-duty, Guard/Reserve, and their spouses, children, and grandchildren", "Application window Jan 1 - Apr 30"]),
    ("VFW Voice of Democracy Audio-Essay Scholarship", "Veterans of Foreign Wars", "civic", "scholarship", "merit",
     ["high-school"], "https://www.vfw.org/community/youth-and-education/youth-scholarships",
     ["Audio-essay competition open to all U.S. students in grades 9-12 (no military affiliation required)", "National first place is a large award; deadline Oct 31"]),
    ("The American Legion Legacy Scholarship", "The American Legion", "civic", "scholarship", "service",
     ["undergraduate", "graduate", "vocational"], "https://www.legion.org/get-involved/scholarships/the-american-legion-legacy-scholarship",
     ["Children of post-9/11 service members who died on active duty or veterans with a 50%+ VA disability rating", "Need-based"]),
    ("DAR Scholarships", "Daughters of the American Revolution", "civic", "scholarship", "merit",
     ["undergraduate", "graduate"], "https://dar.academicworks.com/",
     ["~27 named scholarships, $1,000-$25,000; most do NOT require DAR membership", "U.S. citizens; applications open Nov 1 - Jan 31"]),
    ("Gloria Barron Prize for Young Heroes", "Barron Prize", "foundation", "prize", "service",
     ["high-school"], "https://barronprize.org/apply/",
     ["Ages 8-18 leading a significant service project benefiting people or the environment", "Open to U.S. and Canada residents"]),
    ("National YoungArts Award", "National YoungArts Foundation", "foundation", "scholarship", "merit",
     ["high-school"], "https://youngarts.org/apply/",
     ["Grades 10-12 or ages 15-18; U.S. citizen, PR, or eligible to receive taxable U.S. income", "National competition across 10 arts disciplines"]),
    ("Doodle for Google", "Google", "employer", "prize", "merit",
     ["high-school"], "https://doodles.google.com/d4g/",
     ["U.S. K-12 students; citizen or permanent resident", "National winner receives a college scholarship plus a school tech package"]),
    ("Scholastic Art & Writing Awards", "Alliance for Young Artists & Writers", "foundation", "scholarship", "merit",
     ["high-school"], "https://artandwriting.org/awards/how-to-enter/",
     ["U.S./Canada students grades 7-12; regional then national judging", "National Medalists eligible for scholarships; fee waivers available"]),
    ("Breakthrough Junior Challenge", "Breakthrough Prize Foundation", "foundation", "scholarship", "merit",
     ["high-school"], "https://breakthroughjuniorchallenge.org",
     ["High school students ages 13-18", "Create a 90-second science/math explainer video; large post-secondary scholarship grand prize"]),
    ("National History Day Contest", "National History Day", "foundation", "scholarship", "merit",
     ["high-school"], "https://www.nhd.org",
     ["Students in grades 6-12 nationwide", "100+ cash prizes plus scholarships"]),
    ("Ayn Rand Institute Essay Contests", "Ayn Rand Institute", "foundation", "prize", "merit",
     ["high-school", "undergraduate", "graduate"], "https://aynrand.org/students/essay-contests/",
     ["Students enrolled in school, ages 13+", "Novel-based essay contests (Anthem / The Fountainhead / Atlas Shrugged)"]),
    ("John F. Kennedy Profile in Courage Essay Contest", "John F. Kennedy Library Foundation", "foundation", "prize", "merit",
     ["high-school"], "https://www.jfklibrary.org/learn/education/profile-in-courage-essay-contest",
     ["U.S. high school students grades 9-12 (incl. home school and citizens abroad)", "Essay on an act of political courage by a U.S. elected official"]),
]


def build(name, sponsor, sponsor_type, typ, basis, levels, info_url, notes) -> dict:
    return {
        "id": f"us-{d._slug(name)}",
        "name": name,
        "sponsor": sponsor,
        "sponsor_type": sponsor_type,
        "type": typ,
        "award": {"amount_min": None, "amount_max": None, "currency": "USD", "basis": basis,
                  "renewable": None, "notes": None},
        "deadline": {"type": "annual", "date": None, "notes": "Verify the current cycle's deadline against the source."},
        "eligibility": {"residency": ["US"], "education_level": levels, "fields_of_study": [],
                        "gpa_min": None, "citizenship": [], "other": notes, "tags": ["national"]},
        "geo": {"state": None, "scope": "national", "counties": []},
        "links": {"info_url": info_url, "apply_url": None},
        "provenance": {"source_url": info_url, "source_name": sponsor, "last_verified": TODAY,
                       "verification_method": "research-summary", "added": TODAY},
        "status": "needs-review",
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    existing = d.existing_keys()
    out_dir = d.DATA / "US"
    written = 0
    for entry in CURATED:
        rec = build(*entry)
        name_key = d._slug(rec["name"])
        if name_key in existing:
            print(f"  skip (already have): {rec['name']}")
            continue
        # confirm the official link is live before queueing — never queue a dead source
        html, info = d.fetch(rec["links"]["info_url"])
        if not html:
            print(f"  SKIP (dead link {info}): {rec['name']}  {rec['links']['info_url']}")
            continue
        errors = list(d.VALIDATOR.iter_errors(rec))
        if errors:
            print(f"  SKIP (invalid): {rec['name']} — {errors[0].message}")
            continue
        print(f"  + {rec['id']}")
        if not args.dry_run:
            out_dir.mkdir(parents=True, exist_ok=True)
            (out_dir / f"{rec['id']}.json").write_text(json.dumps(rec, indent=2) + "\n")
            written += 1

    print(f"\n{'(dry run) ' if args.dry_run else ''}{written} record(s) written to data/US/ as needs-review.")


if __name__ == "__main__":
    main()
